/** Required package class namespace */
package view;

/** Required import statements */
import javax.swing.JOptionPane;
import miniGames.RSP;

/**
 * User Interface for RSP
 * 
 * @author u.iwai
 */
public class RSPUI extends javax.swing.JFrame {
    
    // 1 for rock, 2 for scissors, 3 for paper
    private static int userChoice; 
    
    /**
     * Default constructor, sets properties
     */
    public RSPUI() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        jLabel3.setText("Click on the picture");
        // sets it visible
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 50, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/rockPaperScissors.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Click and Chose");

        jLabel3.setFont(new java.awt.Font("UD デジタル 教科書体 NP-R", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * user moves the mouse to select their choice
     * 
     * @param evt changes the label so that it tells the user's choice
     */
    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // Sets text for jLabel3 depending on the location of the mouse
        if (evt.getY() > 0 && evt.getY() < 130) {
            if (evt.getX() > 0 && evt.getX() <= 86) { // rock
                jLabel3.setText("Rock");
                userChoice = 1;
            } else if (evt.getX() > 86 && evt.getX() <= 172) { // scissors
                jLabel3.setText("Scissors");
                userChoice = 2;
            } else if (evt.getX() > 172 && evt.getX() < 240) { // paper
                jLabel3.setText("Paper");
                userChoice = 3;
            } else {
                jLabel3.setText("Click on the picture");
            }
        } else {
            jLabel3.setText("Click on the picture");
        }


    }//GEN-LAST:event_jLabel1MouseMoved

    /**
     * user clicks on a picture, sets a valure for the user's choices
     * 
     * @param evt make it invisible, go to the result display
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Confirms the user's choice
        String message
        = "Your choice: " + jLabel3.getText() + "\n\nClick OK to see the result";
        // Clicked on the picture
        if (evt.getY() > 40 && evt.getY() < 130) {
            // rock
            if (evt.getX() > 0 && evt.getX() <= 86) { 
                userChoice = 1;
                jLabel3.setText("Rock");
            } // scissors
            else if (evt.getX() > 86 && evt.getX() <= 172) { 
                userChoice = 2;
                jLabel3.setText("Scissors");
            } // paper
            else if (evt.getX() > 172 && evt.getX() < 240) { 
                userChoice = 3;
                jLabel3.setText("Paper");
            }
        }
        JOptionPane.showMessageDialog(null, message);
        this.setVisible(false);
        RSP.result();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSPUI().setVisible(true);
            }
        });
    }

    /**
     * Accessor method for userChoice
     *
     * @return user's choice (1 for rock, 2 for scissors, 3 for paper)
     */
    public static int getUserChoice() {
        return userChoice;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
